# Generated by Django 2.2.5 on 2020-01-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pretty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('na', models.CharField(max_length=200)),
                ('ag', models.CharField(max_length=200)),
                ('pw', models.CharField(max_length=200)),
            ],
        ),
    ]
